<?php
$data = array (
  996 => 
  array (
    'cat_id' => '996',
    'cat_name' => '进口零食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '996',
    'name' => '进口零食',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '家用电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '家用电器',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '大 家 电',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '90',
    'name' => '大 家 电',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '消毒柜/洗碗机',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '104',
    'name' => '消毒柜/洗碗机',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '空调',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '96',
    'name' => '空调',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '酒柜/冷柜',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '105',
    'name' => '酒柜/冷柜',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '冰箱',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '97',
    'name' => '冰箱',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '热水器',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => '热水器',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '个护健康',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '93',
    'name' => '个护健康',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '剃须刀',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '139',
    'name' => '剃须刀',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '血压计',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '148',
    'name' => '血压计',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '口腔护理',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '140',
    'name' => '口腔护理',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => '健康秤/厨房秤',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '149',
    'name' => '健康秤/厨房秤',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '美容',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '143',
    'name' => '美容',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => '体温计',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '151',
    'name' => '体温计',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => '美发',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '144',
    'name' => '美发',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '厨房电器',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '92',
    'name' => '厨房电器',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '煮蛋器',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '132',
    'name' => '煮蛋器',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '电压力锅',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '122',
    'name' => '电压力锅',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '电水壶/热水瓶',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '134',
    'name' => '电水壶/热水瓶',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '微波炉',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '127',
    'name' => '微波炉',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '电炖锅',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '135',
    'name' => '电炖锅',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '料理/榨汁机',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '128',
    'name' => '料理/榨汁机',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '运动户外',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '运动户外',
  ),
  543 => 
  array (
    'cat_id' => '543',
    'cat_name' => '运动服饰',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '543',
    'name' => '运动服饰',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '生活电器',
    'measure_unit' => '',
    'parent_id' => '543',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 3,
    'id' => '91',
    'name' => '生活电器',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '饮水机',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 4,
    'id' => '110',
    'name' => '饮水机',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '收录/音机',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 4,
    'id' => '116',
    'name' => '收录/音机',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '除湿/干衣机',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 4,
    'id' => '119',
    'name' => '除湿/干衣机',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '净化器',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 4,
    'id' => '109',
    'name' => '净化器',
  ),
);
?>